CREATE TABLE users (
    id SERIAL PRIMARY KEY ,
    cpf VARCHAR(11) NOT NULL UNIQUE,
    full_name VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    latitude DECIMAL(9,6) NOT NULL,
    longitude DECIMAL(9,6) NOT NULL,
    role VARCHAR(15) CHECK (role IN ('ADMIN', 'DELIVERY_PERSON')) NOT NULL,
    vehicle_plate VARCHAR(7) UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
